# Build with Node.js
FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# We receive the variable from docker-compose and expose it to Vite
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

RUN npm run build

# Lightweight web server with Nginx
FROM nginx:alpine
# Copy the build generated by Vite 
COPY --from=build /app/dist /usr/share/nginx/html
# Override Nginx's default configuration with ours
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]