server {
    listen 80;
    server_name my.redcheckapp.com;

    # Cabeceras para no perder la IP real del usuario
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # 1. Enrutamiento API directo al backend de Spring Boot
    location /auth/ { proxy_pass http://backend:8080; }
    location /users/ { proxy_pass http://backend:8080; }
    location /subjects { proxy_pass http://backend:8080; }
    location /tasks { proxy_pass http://backend:8080; }
    location /recurring_tasks { proxy_pass http://backend:8080; }
    location /progress_records { proxy_pass http://backend:8080; }
    location /notifications { proxy_pass http://backend:8080; }
    location /ai_responses { proxy_pass http://backend:8080; }
    location /ai { proxy_pass http://backend:8080; }
    location /progress { proxy_pass http://backend:8080; }
    location /v3/ { proxy_pass http://backend:8080; }
    location /swagger-ui/ { proxy_pass http://backend:8080; }

    # 2. React / Vite
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html; 
    }
}