server {
    listen 80;
    # Escuchamos a tu dominio, con y sin 'www', y mantenemos localhost por si acaso
    server_name redcheck.es www.redcheck.es localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Makes React Router work when reloading the page:
        try_files $uri $uri/ /index.html; 
    }
}