# Redirigir todo el tráfico HTTP (80) hacia HTTPS (443)
server {
    listen 80;
    server_name redcheck.es www.redcheck.es;
    return 301 https://$host$request_uri;
}

# Servidor principal en HTTPS
server {
    listen 443 ssl;
    server_name redcheck.es www.redcheck.es;

    # Rutas de los certificados que acabamos de generar
    ssl_certificate /etc/letsencrypt/live/redcheck.es/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/redcheck.es/privkey.pem;

    # 1. Redirigir las llamadas de la API directamente al contenedor del backend
    location /auth/ { proxy_pass http://redcheck-backend:8080; }
    location /users/ { proxy_pass http://redcheck-backend:8080; }
    location /v3/ { proxy_pass http://redcheck-backend:8080; }
    location /swagger-ui/ { proxy_pass http://redcheck-backend:8080; }

    # 2. El resto del tráfico va a tu frontend (React/Vite)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html; 
    }
}