export interface LoginForm {
    emailOrUsername: string;
    password: string;
}

export interface AuthResponse {
    token: string;
}

export interface GoogleAuthRequest {
    idToken: string;
}

export interface RegisterForm {
    username: string;
    email: string;
    password: string;
}

export interface SubjectResponse {
    id: number;
    name: string;
    description: string | null;
    deleted: boolean;
    archived: boolean;
}

export type TaskPriority = "LOW" | "MEDIUM" | "HIGH";

export interface TaskResponse {
    id: number;
    title: string;
    description: string | null;
    assignedDate: string;
    deadline: string | null;
    completedDate: string | null;
    completed: boolean;
    deleted: boolean;
    overdue: boolean;
    subjectId: number;
    priority: TaskPriority;
}

export interface TaskRequest {
    title: string;
    description: string | null;
    deadline: string | null;
    // Optional: omitting it means "default to MEDIUM" on create, or "keep
    // the task's current priority" on update — see redcheck-backend's
    // TaskService (createTask/updateTask).
    priority?: TaskPriority;
}

export interface SubjectWithTasks extends SubjectResponse {
    tasks: TaskResponse[];
}

export interface EventCategoryResponse {
    id: number;
    name: string;
    color: string; // hex, e.g. "#4F46E5"
}

export interface EventCategoryRequest {
    name: string;
    color: string;
}

// Unlike TaskResponse.deadline (a single point in time), a calendar event
// always has both a start and an end — a punctual event (no explicit end
// picked by the user) is stored with endDateTime equal to startDateTime,
// never null, so every event is a well-formed interval (see
// redcheck-backend's CalendarEvent entity).
export interface CalendarEventResponse {
    id: number;
    title: string;
    description: string | null;
    startDateTime: string;
    endDateTime: string;
    allDay: boolean;
    categoryId: number | null;
    // Non-null when this occurrence was generated by a recurring event
    // routine — see RecurringCalendarEventRequest below.
    recurringEventId: number | null;
}

export interface CalendarEventRequest {
    title: string;
    description: string | null;
    startDateTime: string;
    endDateTime: string | null;
    allDay: boolean;
    categoryId: number | null;
}

export interface RecurringCalendarEventResponse {
    id: number;
    title: string;
    description: string | null;
    allDay: boolean;
    time: string | null; // "HH:mm:ss", ignored when allDay
    durationMinutes: number | null; // ignored when allDay
    frequency: string;
    endDate: string | null; // "YYYY-MM-DD", routine auto-deactivates once reached
    active: boolean;
    createdDate: string;
    latestGeneratedDate: string;
    nextOccurrence: string | null;
    categoryId: number | null;
}

export interface RecurringCalendarEventRequest {
    title: string;
    description: string | null;
    allDay: boolean;
    time?: string | null;
    durationMinutes?: number | null;
    frequency: string;
    endDate?: string | null;
    categoryId: number | null;
}

export interface UserResponse {
    username: string;
    alias: string;
    email: string;
    hasPassword: boolean;
}

export interface SubjectRequest {
    name: string;
    description: string | null;
}

export interface ProgressRecord {
    date: string; // "YYYY-MM-DD"
    totalTasks: number;
    completedTasks: number;
    completionRate: number;
}

export interface RecurringTaskResponse {
    id: number,
    title: string,
    description: string | null,
    frequency: string,
    time: string | null, // "HH:mm:ss", applied to every generated task's deadline
    endDate: string | null, // "YYYY-MM-DD", routine auto-deactivates once reached
    active: boolean,
    createdDate: string,
    latestGeneratedDate: string,
    nextOccurrence: string | null, // server-computed preview, ISO datetime
    currentStreak: number,
    longestStreak: number,
    completionRate: number, // 0-1
    totalGenerated: number,
    totalCompleted: number,
    subjectId: number
}

// We define the exact structure that the backend will send us
export interface SubjectStat {
    id: number | string;
    name: string;
    percent: number;
    colorClass: string;       // Ex: "bg-red-500"
    hoverTextClass: string;   // Ex: "group-hover:text-red-600"
}

export interface SmartCheckPlanItem {
    id: number;
    ordenDefinido: number;
    razonPrioridad: string;
}

export interface SmartCheckAiData {
    nivelRiesgo: string;
    mensajeApoyo: string;
    planDeHoy: SmartCheckPlanItem[];
}

export type FeedbackCategory = "BUG" | "SUGGESTION" | "PRAISE" | "OTHER";

export interface FeedbackRequest {
    category: FeedbackCategory;
    message: string;
}

export interface FeedbackResponse {
    id: number;
    category: FeedbackCategory;
    message: string;
    createdDate: string;
}